// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alakoro_sensing.proto

#include "alakoro_sensing.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace alakoro {
namespace pb {
PROTOBUF_CONSTEXPR AcquisitionMetadata::AcquisitionMetadata(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.units_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.start_time_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sampling_rate_hz_)*/0
  , /*decltype(_impl_.spatial_resolution_m_)*/0
  , /*decltype(_impl_.gauge_length_m_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AcquisitionMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AcquisitionMetadataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AcquisitionMetadataDefaultTypeInternal() {}
  union {
    AcquisitionMetadata _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AcquisitionMetadataDefaultTypeInternal _AcquisitionMetadata_default_instance_;
PROTOBUF_CONSTEXPR SensingData::SensingData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_f32_)*/{}
  , /*decltype(_impl_.data_f64_)*/{}
  , /*decltype(_impl_.dtype_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.metadata_)*/nullptr
  , /*decltype(_impl_.n_times_)*/uint64_t{0u}
  , /*decltype(_impl_.n_channels_)*/uint64_t{0u}
  , /*decltype(_impl_.modality_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SensingDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SensingDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SensingDataDefaultTypeInternal() {}
  union {
    SensingData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SensingDataDefaultTypeInternal _SensingData_default_instance_;
}  // namespace pb
}  // namespace alakoro
static ::_pb::Metadata file_level_metadata_alakoro_5fsensing_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_alakoro_5fsensing_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_alakoro_5fsensing_2eproto = nullptr;

const uint32_t TableStruct_alakoro_5fsensing_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::AcquisitionMetadata, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::AcquisitionMetadata, _impl_.sampling_rate_hz_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::AcquisitionMetadata, _impl_.spatial_resolution_m_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::AcquisitionMetadata, _impl_.gauge_length_m_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::AcquisitionMetadata, _impl_.units_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::AcquisitionMetadata, _impl_.start_time_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::SensingData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::SensingData, _impl_.modality_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::SensingData, _impl_.n_times_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::SensingData, _impl_.n_channels_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::SensingData, _impl_.metadata_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::SensingData, _impl_.dtype_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::SensingData, _impl_.data_f32_),
  PROTOBUF_FIELD_OFFSET(::alakoro::pb::SensingData, _impl_.data_f64_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::alakoro::pb::AcquisitionMetadata)},
  { 11, -1, -1, sizeof(::alakoro::pb::SensingData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::alakoro::pb::_AcquisitionMetadata_default_instance_._instance,
  &::alakoro::pb::_SensingData_default_instance_._instance,
};

const char descriptor_table_protodef_alakoro_5fsensing_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025alakoro_sensing.proto\022\nalakoro.pb\"\210\001\n\023"
  "AcquisitionMetadata\022\030\n\020sampling_rate_hz\030"
  "\001 \001(\001\022\034\n\024spatial_resolution_m\030\002 \001(\001\022\026\n\016g"
  "auge_length_m\030\003 \001(\001\022\r\n\005units\030\004 \001(\t\022\022\n\nst"
  "art_time\030\005 \001(\t\"\300\001\n\013SensingData\022&\n\010modali"
  "ty\030\001 \001(\0162\024.alakoro.pb.Modality\022\017\n\007n_time"
  "s\030\002 \001(\004\022\022\n\nn_channels\030\003 \001(\004\0221\n\010metadata\030"
  "\004 \001(\0132\037.alakoro.pb.AcquisitionMetadata\022\r"
  "\n\005dtype\030\005 \001(\t\022\020\n\010data_f32\030\006 \003(\002\022\020\n\010data_"
  "f64\030\007 \003(\001*%\n\010Modality\022\007\n\003DAS\020\000\022\007\n\003DTS\020\001\022"
  "\007\n\003DSS\020\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_alakoro_5fsensing_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_alakoro_5fsensing_2eproto = {
    false, false, 416, descriptor_table_protodef_alakoro_5fsensing_2eproto,
    "alakoro_sensing.proto",
    &descriptor_table_alakoro_5fsensing_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_alakoro_5fsensing_2eproto::offsets,
    file_level_metadata_alakoro_5fsensing_2eproto, file_level_enum_descriptors_alakoro_5fsensing_2eproto,
    file_level_service_descriptors_alakoro_5fsensing_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_alakoro_5fsensing_2eproto_getter() {
  return &descriptor_table_alakoro_5fsensing_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_alakoro_5fsensing_2eproto(&descriptor_table_alakoro_5fsensing_2eproto);
namespace alakoro {
namespace pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Modality_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_alakoro_5fsensing_2eproto);
  return file_level_enum_descriptors_alakoro_5fsensing_2eproto[0];
}
bool Modality_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class AcquisitionMetadata::_Internal {
 public:
};

AcquisitionMetadata::AcquisitionMetadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:alakoro.pb.AcquisitionMetadata)
}
AcquisitionMetadata::AcquisitionMetadata(const AcquisitionMetadata& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AcquisitionMetadata* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.units_){}
    , decltype(_impl_.start_time_){}
    , decltype(_impl_.sampling_rate_hz_){}
    , decltype(_impl_.spatial_resolution_m_){}
    , decltype(_impl_.gauge_length_m_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.units_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.units_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_units().empty()) {
    _this->_impl_.units_.Set(from._internal_units(), 
      _this->GetArenaForAllocation());
  }
  _impl_.start_time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.start_time_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_start_time().empty()) {
    _this->_impl_.start_time_.Set(from._internal_start_time(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.sampling_rate_hz_, &from._impl_.sampling_rate_hz_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.gauge_length_m_) -
    reinterpret_cast<char*>(&_impl_.sampling_rate_hz_)) + sizeof(_impl_.gauge_length_m_));
  // @@protoc_insertion_point(copy_constructor:alakoro.pb.AcquisitionMetadata)
}

inline void AcquisitionMetadata::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.units_){}
    , decltype(_impl_.start_time_){}
    , decltype(_impl_.sampling_rate_hz_){0}
    , decltype(_impl_.spatial_resolution_m_){0}
    , decltype(_impl_.gauge_length_m_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.units_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.units_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.start_time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.start_time_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AcquisitionMetadata::~AcquisitionMetadata() {
  // @@protoc_insertion_point(destructor:alakoro.pb.AcquisitionMetadata)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AcquisitionMetadata::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.units_.Destroy();
  _impl_.start_time_.Destroy();
}

void AcquisitionMetadata::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AcquisitionMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:alakoro.pb.AcquisitionMetadata)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.units_.ClearToEmpty();
  _impl_.start_time_.ClearToEmpty();
  ::memset(&_impl_.sampling_rate_hz_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.gauge_length_m_) -
      reinterpret_cast<char*>(&_impl_.sampling_rate_hz_)) + sizeof(_impl_.gauge_length_m_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AcquisitionMetadata::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double sampling_rate_hz = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.sampling_rate_hz_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double spatial_resolution_m = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.spatial_resolution_m_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double gauge_length_m = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.gauge_length_m_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // string units = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_units();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "alakoro.pb.AcquisitionMetadata.units"));
        } else
          goto handle_unusual;
        continue;
      // string start_time = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_start_time();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "alakoro.pb.AcquisitionMetadata.start_time"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AcquisitionMetadata::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:alakoro.pb.AcquisitionMetadata)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double sampling_rate_hz = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sampling_rate_hz = this->_internal_sampling_rate_hz();
  uint64_t raw_sampling_rate_hz;
  memcpy(&raw_sampling_rate_hz, &tmp_sampling_rate_hz, sizeof(tmp_sampling_rate_hz));
  if (raw_sampling_rate_hz != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_sampling_rate_hz(), target);
  }

  // double spatial_resolution_m = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_spatial_resolution_m = this->_internal_spatial_resolution_m();
  uint64_t raw_spatial_resolution_m;
  memcpy(&raw_spatial_resolution_m, &tmp_spatial_resolution_m, sizeof(tmp_spatial_resolution_m));
  if (raw_spatial_resolution_m != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_spatial_resolution_m(), target);
  }

  // double gauge_length_m = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_gauge_length_m = this->_internal_gauge_length_m();
  uint64_t raw_gauge_length_m;
  memcpy(&raw_gauge_length_m, &tmp_gauge_length_m, sizeof(tmp_gauge_length_m));
  if (raw_gauge_length_m != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_gauge_length_m(), target);
  }

  // string units = 4;
  if (!this->_internal_units().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_units().data(), static_cast<int>(this->_internal_units().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "alakoro.pb.AcquisitionMetadata.units");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_units(), target);
  }

  // string start_time = 5;
  if (!this->_internal_start_time().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_start_time().data(), static_cast<int>(this->_internal_start_time().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "alakoro.pb.AcquisitionMetadata.start_time");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_start_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:alakoro.pb.AcquisitionMetadata)
  return target;
}

size_t AcquisitionMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:alakoro.pb.AcquisitionMetadata)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string units = 4;
  if (!this->_internal_units().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_units());
  }

  // string start_time = 5;
  if (!this->_internal_start_time().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_start_time());
  }

  // double sampling_rate_hz = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sampling_rate_hz = this->_internal_sampling_rate_hz();
  uint64_t raw_sampling_rate_hz;
  memcpy(&raw_sampling_rate_hz, &tmp_sampling_rate_hz, sizeof(tmp_sampling_rate_hz));
  if (raw_sampling_rate_hz != 0) {
    total_size += 1 + 8;
  }

  // double spatial_resolution_m = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_spatial_resolution_m = this->_internal_spatial_resolution_m();
  uint64_t raw_spatial_resolution_m;
  memcpy(&raw_spatial_resolution_m, &tmp_spatial_resolution_m, sizeof(tmp_spatial_resolution_m));
  if (raw_spatial_resolution_m != 0) {
    total_size += 1 + 8;
  }

  // double gauge_length_m = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_gauge_length_m = this->_internal_gauge_length_m();
  uint64_t raw_gauge_length_m;
  memcpy(&raw_gauge_length_m, &tmp_gauge_length_m, sizeof(tmp_gauge_length_m));
  if (raw_gauge_length_m != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AcquisitionMetadata::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AcquisitionMetadata::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AcquisitionMetadata::GetClassData() const { return &_class_data_; }


void AcquisitionMetadata::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AcquisitionMetadata*>(&to_msg);
  auto& from = static_cast<const AcquisitionMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:alakoro.pb.AcquisitionMetadata)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_units().empty()) {
    _this->_internal_set_units(from._internal_units());
  }
  if (!from._internal_start_time().empty()) {
    _this->_internal_set_start_time(from._internal_start_time());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_sampling_rate_hz = from._internal_sampling_rate_hz();
  uint64_t raw_sampling_rate_hz;
  memcpy(&raw_sampling_rate_hz, &tmp_sampling_rate_hz, sizeof(tmp_sampling_rate_hz));
  if (raw_sampling_rate_hz != 0) {
    _this->_internal_set_sampling_rate_hz(from._internal_sampling_rate_hz());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_spatial_resolution_m = from._internal_spatial_resolution_m();
  uint64_t raw_spatial_resolution_m;
  memcpy(&raw_spatial_resolution_m, &tmp_spatial_resolution_m, sizeof(tmp_spatial_resolution_m));
  if (raw_spatial_resolution_m != 0) {
    _this->_internal_set_spatial_resolution_m(from._internal_spatial_resolution_m());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_gauge_length_m = from._internal_gauge_length_m();
  uint64_t raw_gauge_length_m;
  memcpy(&raw_gauge_length_m, &tmp_gauge_length_m, sizeof(tmp_gauge_length_m));
  if (raw_gauge_length_m != 0) {
    _this->_internal_set_gauge_length_m(from._internal_gauge_length_m());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AcquisitionMetadata::CopyFrom(const AcquisitionMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:alakoro.pb.AcquisitionMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AcquisitionMetadata::IsInitialized() const {
  return true;
}

void AcquisitionMetadata::InternalSwap(AcquisitionMetadata* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.units_, lhs_arena,
      &other->_impl_.units_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.start_time_, lhs_arena,
      &other->_impl_.start_time_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AcquisitionMetadata, _impl_.gauge_length_m_)
      + sizeof(AcquisitionMetadata::_impl_.gauge_length_m_)
      - PROTOBUF_FIELD_OFFSET(AcquisitionMetadata, _impl_.sampling_rate_hz_)>(
          reinterpret_cast<char*>(&_impl_.sampling_rate_hz_),
          reinterpret_cast<char*>(&other->_impl_.sampling_rate_hz_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AcquisitionMetadata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_alakoro_5fsensing_2eproto_getter, &descriptor_table_alakoro_5fsensing_2eproto_once,
      file_level_metadata_alakoro_5fsensing_2eproto[0]);
}

// ===================================================================

class SensingData::_Internal {
 public:
  static const ::alakoro::pb::AcquisitionMetadata& metadata(const SensingData* msg);
};

const ::alakoro::pb::AcquisitionMetadata&
SensingData::_Internal::metadata(const SensingData* msg) {
  return *msg->_impl_.metadata_;
}
SensingData::SensingData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:alakoro.pb.SensingData)
}
SensingData::SensingData(const SensingData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SensingData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_f32_){from._impl_.data_f32_}
    , decltype(_impl_.data_f64_){from._impl_.data_f64_}
    , decltype(_impl_.dtype_){}
    , decltype(_impl_.metadata_){nullptr}
    , decltype(_impl_.n_times_){}
    , decltype(_impl_.n_channels_){}
    , decltype(_impl_.modality_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.dtype_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dtype_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_dtype().empty()) {
    _this->_impl_.dtype_.Set(from._internal_dtype(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_metadata()) {
    _this->_impl_.metadata_ = new ::alakoro::pb::AcquisitionMetadata(*from._impl_.metadata_);
  }
  ::memcpy(&_impl_.n_times_, &from._impl_.n_times_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.modality_) -
    reinterpret_cast<char*>(&_impl_.n_times_)) + sizeof(_impl_.modality_));
  // @@protoc_insertion_point(copy_constructor:alakoro.pb.SensingData)
}

inline void SensingData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_f32_){arena}
    , decltype(_impl_.data_f64_){arena}
    , decltype(_impl_.dtype_){}
    , decltype(_impl_.metadata_){nullptr}
    , decltype(_impl_.n_times_){uint64_t{0u}}
    , decltype(_impl_.n_channels_){uint64_t{0u}}
    , decltype(_impl_.modality_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.dtype_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dtype_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SensingData::~SensingData() {
  // @@protoc_insertion_point(destructor:alakoro.pb.SensingData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SensingData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_f32_.~RepeatedField();
  _impl_.data_f64_.~RepeatedField();
  _impl_.dtype_.Destroy();
  if (this != internal_default_instance()) delete _impl_.metadata_;
}

void SensingData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SensingData::Clear() {
// @@protoc_insertion_point(message_clear_start:alakoro.pb.SensingData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_f32_.Clear();
  _impl_.data_f64_.Clear();
  _impl_.dtype_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.metadata_ != nullptr) {
    delete _impl_.metadata_;
  }
  _impl_.metadata_ = nullptr;
  ::memset(&_impl_.n_times_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.modality_) -
      reinterpret_cast<char*>(&_impl_.n_times_)) + sizeof(_impl_.modality_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SensingData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .alakoro.pb.Modality modality = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_modality(static_cast<::alakoro::pb::Modality>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 n_times = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.n_times_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 n_channels = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.n_channels_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .alakoro.pb.AcquisitionMetadata metadata = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_metadata(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string dtype = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_dtype();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "alakoro.pb.SensingData.dtype"));
        } else
          goto handle_unusual;
        continue;
      // repeated float data_f32 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_data_f32(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 53) {
          _internal_add_data_f32(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated double data_f64 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_data_f64(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 57) {
          _internal_add_data_f64(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SensingData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:alakoro.pb.SensingData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .alakoro.pb.Modality modality = 1;
  if (this->_internal_modality() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_modality(), target);
  }

  // uint64 n_times = 2;
  if (this->_internal_n_times() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_n_times(), target);
  }

  // uint64 n_channels = 3;
  if (this->_internal_n_channels() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_n_channels(), target);
  }

  // .alakoro.pb.AcquisitionMetadata metadata = 4;
  if (this->_internal_has_metadata()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::metadata(this),
        _Internal::metadata(this).GetCachedSize(), target, stream);
  }

  // string dtype = 5;
  if (!this->_internal_dtype().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_dtype().data(), static_cast<int>(this->_internal_dtype().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "alakoro.pb.SensingData.dtype");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_dtype(), target);
  }

  // repeated float data_f32 = 6;
  if (this->_internal_data_f32_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_data_f32(), target);
  }

  // repeated double data_f64 = 7;
  if (this->_internal_data_f64_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_data_f64(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:alakoro.pb.SensingData)
  return target;
}

size_t SensingData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:alakoro.pb.SensingData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float data_f32 = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_data_f32_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated double data_f64 = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_data_f64_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string dtype = 5;
  if (!this->_internal_dtype().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_dtype());
  }

  // .alakoro.pb.AcquisitionMetadata metadata = 4;
  if (this->_internal_has_metadata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.metadata_);
  }

  // uint64 n_times = 2;
  if (this->_internal_n_times() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_n_times());
  }

  // uint64 n_channels = 3;
  if (this->_internal_n_channels() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_n_channels());
  }

  // .alakoro.pb.Modality modality = 1;
  if (this->_internal_modality() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_modality());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SensingData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SensingData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SensingData::GetClassData() const { return &_class_data_; }


void SensingData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SensingData*>(&to_msg);
  auto& from = static_cast<const SensingData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:alakoro.pb.SensingData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_f32_.MergeFrom(from._impl_.data_f32_);
  _this->_impl_.data_f64_.MergeFrom(from._impl_.data_f64_);
  if (!from._internal_dtype().empty()) {
    _this->_internal_set_dtype(from._internal_dtype());
  }
  if (from._internal_has_metadata()) {
    _this->_internal_mutable_metadata()->::alakoro::pb::AcquisitionMetadata::MergeFrom(
        from._internal_metadata());
  }
  if (from._internal_n_times() != 0) {
    _this->_internal_set_n_times(from._internal_n_times());
  }
  if (from._internal_n_channels() != 0) {
    _this->_internal_set_n_channels(from._internal_n_channels());
  }
  if (from._internal_modality() != 0) {
    _this->_internal_set_modality(from._internal_modality());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SensingData::CopyFrom(const SensingData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:alakoro.pb.SensingData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensingData::IsInitialized() const {
  return true;
}

void SensingData::InternalSwap(SensingData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_f32_.InternalSwap(&other->_impl_.data_f32_);
  _impl_.data_f64_.InternalSwap(&other->_impl_.data_f64_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.dtype_, lhs_arena,
      &other->_impl_.dtype_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SensingData, _impl_.modality_)
      + sizeof(SensingData::_impl_.modality_)
      - PROTOBUF_FIELD_OFFSET(SensingData, _impl_.metadata_)>(
          reinterpret_cast<char*>(&_impl_.metadata_),
          reinterpret_cast<char*>(&other->_impl_.metadata_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SensingData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_alakoro_5fsensing_2eproto_getter, &descriptor_table_alakoro_5fsensing_2eproto_once,
      file_level_metadata_alakoro_5fsensing_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace alakoro
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::alakoro::pb::AcquisitionMetadata*
Arena::CreateMaybeMessage< ::alakoro::pb::AcquisitionMetadata >(Arena* arena) {
  return Arena::CreateMessageInternal< ::alakoro::pb::AcquisitionMetadata >(arena);
}
template<> PROTOBUF_NOINLINE ::alakoro::pb::SensingData*
Arena::CreateMaybeMessage< ::alakoro::pb::SensingData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::alakoro::pb::SensingData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
