// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alakoro_sensing.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_alakoro_5fsensing_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_alakoro_5fsensing_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_alakoro_5fsensing_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_alakoro_5fsensing_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_alakoro_5fsensing_2eproto;
namespace alakoro {
namespace pb {
class AcquisitionMetadata;
struct AcquisitionMetadataDefaultTypeInternal;
extern AcquisitionMetadataDefaultTypeInternal _AcquisitionMetadata_default_instance_;
class SensingData;
struct SensingDataDefaultTypeInternal;
extern SensingDataDefaultTypeInternal _SensingData_default_instance_;
}  // namespace pb
}  // namespace alakoro
PROTOBUF_NAMESPACE_OPEN
template<> ::alakoro::pb::AcquisitionMetadata* Arena::CreateMaybeMessage<::alakoro::pb::AcquisitionMetadata>(Arena*);
template<> ::alakoro::pb::SensingData* Arena::CreateMaybeMessage<::alakoro::pb::SensingData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace alakoro {
namespace pb {

enum Modality : int {
  DAS = 0,
  DTS = 1,
  DSS = 2,
  Modality_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Modality_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Modality_IsValid(int value);
constexpr Modality Modality_MIN = DAS;
constexpr Modality Modality_MAX = DSS;
constexpr int Modality_ARRAYSIZE = Modality_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Modality_descriptor();
template<typename T>
inline const std::string& Modality_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Modality>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Modality_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Modality_descriptor(), enum_t_value);
}
inline bool Modality_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Modality* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Modality>(
    Modality_descriptor(), name, value);
}
// ===================================================================

class AcquisitionMetadata final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:alakoro.pb.AcquisitionMetadata) */ {
 public:
  inline AcquisitionMetadata() : AcquisitionMetadata(nullptr) {}
  ~AcquisitionMetadata() override;
  explicit PROTOBUF_CONSTEXPR AcquisitionMetadata(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AcquisitionMetadata(const AcquisitionMetadata& from);
  AcquisitionMetadata(AcquisitionMetadata&& from) noexcept
    : AcquisitionMetadata() {
    *this = ::std::move(from);
  }

  inline AcquisitionMetadata& operator=(const AcquisitionMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline AcquisitionMetadata& operator=(AcquisitionMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AcquisitionMetadata& default_instance() {
    return *internal_default_instance();
  }
  static inline const AcquisitionMetadata* internal_default_instance() {
    return reinterpret_cast<const AcquisitionMetadata*>(
               &_AcquisitionMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AcquisitionMetadata& a, AcquisitionMetadata& b) {
    a.Swap(&b);
  }
  inline void Swap(AcquisitionMetadata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AcquisitionMetadata* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AcquisitionMetadata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AcquisitionMetadata>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AcquisitionMetadata& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AcquisitionMetadata& from) {
    AcquisitionMetadata::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AcquisitionMetadata* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "alakoro.pb.AcquisitionMetadata";
  }
  protected:
  explicit AcquisitionMetadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnitsFieldNumber = 4,
    kStartTimeFieldNumber = 5,
    kSamplingRateHzFieldNumber = 1,
    kSpatialResolutionMFieldNumber = 2,
    kGaugeLengthMFieldNumber = 3,
  };
  // string units = 4;
  void clear_units();
  const std::string& units() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_units(ArgT0&& arg0, ArgT... args);
  std::string* mutable_units();
  PROTOBUF_NODISCARD std::string* release_units();
  void set_allocated_units(std::string* units);
  private:
  const std::string& _internal_units() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_units(const std::string& value);
  std::string* _internal_mutable_units();
  public:

  // string start_time = 5;
  void clear_start_time();
  const std::string& start_time() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_start_time(ArgT0&& arg0, ArgT... args);
  std::string* mutable_start_time();
  PROTOBUF_NODISCARD std::string* release_start_time();
  void set_allocated_start_time(std::string* start_time);
  private:
  const std::string& _internal_start_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_start_time(const std::string& value);
  std::string* _internal_mutable_start_time();
  public:

  // double sampling_rate_hz = 1;
  void clear_sampling_rate_hz();
  double sampling_rate_hz() const;
  void set_sampling_rate_hz(double value);
  private:
  double _internal_sampling_rate_hz() const;
  void _internal_set_sampling_rate_hz(double value);
  public:

  // double spatial_resolution_m = 2;
  void clear_spatial_resolution_m();
  double spatial_resolution_m() const;
  void set_spatial_resolution_m(double value);
  private:
  double _internal_spatial_resolution_m() const;
  void _internal_set_spatial_resolution_m(double value);
  public:

  // double gauge_length_m = 3;
  void clear_gauge_length_m();
  double gauge_length_m() const;
  void set_gauge_length_m(double value);
  private:
  double _internal_gauge_length_m() const;
  void _internal_set_gauge_length_m(double value);
  public:

  // @@protoc_insertion_point(class_scope:alakoro.pb.AcquisitionMetadata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr units_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr start_time_;
    double sampling_rate_hz_;
    double spatial_resolution_m_;
    double gauge_length_m_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_alakoro_5fsensing_2eproto;
};
// -------------------------------------------------------------------

class SensingData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:alakoro.pb.SensingData) */ {
 public:
  inline SensingData() : SensingData(nullptr) {}
  ~SensingData() override;
  explicit PROTOBUF_CONSTEXPR SensingData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SensingData(const SensingData& from);
  SensingData(SensingData&& from) noexcept
    : SensingData() {
    *this = ::std::move(from);
  }

  inline SensingData& operator=(const SensingData& from) {
    CopyFrom(from);
    return *this;
  }
  inline SensingData& operator=(SensingData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SensingData& default_instance() {
    return *internal_default_instance();
  }
  static inline const SensingData* internal_default_instance() {
    return reinterpret_cast<const SensingData*>(
               &_SensingData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SensingData& a, SensingData& b) {
    a.Swap(&b);
  }
  inline void Swap(SensingData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SensingData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SensingData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SensingData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SensingData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SensingData& from) {
    SensingData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SensingData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "alakoro.pb.SensingData";
  }
  protected:
  explicit SensingData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataF32FieldNumber = 6,
    kDataF64FieldNumber = 7,
    kDtypeFieldNumber = 5,
    kMetadataFieldNumber = 4,
    kNTimesFieldNumber = 2,
    kNChannelsFieldNumber = 3,
    kModalityFieldNumber = 1,
  };
  // repeated float data_f32 = 6;
  int data_f32_size() const;
  private:
  int _internal_data_f32_size() const;
  public:
  void clear_data_f32();
  private:
  float _internal_data_f32(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_data_f32() const;
  void _internal_add_data_f32(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_data_f32();
  public:
  float data_f32(int index) const;
  void set_data_f32(int index, float value);
  void add_data_f32(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      data_f32() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_data_f32();

  // repeated double data_f64 = 7;
  int data_f64_size() const;
  private:
  int _internal_data_f64_size() const;
  public:
  void clear_data_f64();
  private:
  double _internal_data_f64(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_data_f64() const;
  void _internal_add_data_f64(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_data_f64();
  public:
  double data_f64(int index) const;
  void set_data_f64(int index, double value);
  void add_data_f64(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      data_f64() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_data_f64();

  // string dtype = 5;
  void clear_dtype();
  const std::string& dtype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dtype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dtype();
  PROTOBUF_NODISCARD std::string* release_dtype();
  void set_allocated_dtype(std::string* dtype);
  private:
  const std::string& _internal_dtype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dtype(const std::string& value);
  std::string* _internal_mutable_dtype();
  public:

  // .alakoro.pb.AcquisitionMetadata metadata = 4;
  bool has_metadata() const;
  private:
  bool _internal_has_metadata() const;
  public:
  void clear_metadata();
  const ::alakoro::pb::AcquisitionMetadata& metadata() const;
  PROTOBUF_NODISCARD ::alakoro::pb::AcquisitionMetadata* release_metadata();
  ::alakoro::pb::AcquisitionMetadata* mutable_metadata();
  void set_allocated_metadata(::alakoro::pb::AcquisitionMetadata* metadata);
  private:
  const ::alakoro::pb::AcquisitionMetadata& _internal_metadata() const;
  ::alakoro::pb::AcquisitionMetadata* _internal_mutable_metadata();
  public:
  void unsafe_arena_set_allocated_metadata(
      ::alakoro::pb::AcquisitionMetadata* metadata);
  ::alakoro::pb::AcquisitionMetadata* unsafe_arena_release_metadata();

  // uint64 n_times = 2;
  void clear_n_times();
  uint64_t n_times() const;
  void set_n_times(uint64_t value);
  private:
  uint64_t _internal_n_times() const;
  void _internal_set_n_times(uint64_t value);
  public:

  // uint64 n_channels = 3;
  void clear_n_channels();
  uint64_t n_channels() const;
  void set_n_channels(uint64_t value);
  private:
  uint64_t _internal_n_channels() const;
  void _internal_set_n_channels(uint64_t value);
  public:

  // .alakoro.pb.Modality modality = 1;
  void clear_modality();
  ::alakoro::pb::Modality modality() const;
  void set_modality(::alakoro::pb::Modality value);
  private:
  ::alakoro::pb::Modality _internal_modality() const;
  void _internal_set_modality(::alakoro::pb::Modality value);
  public:

  // @@protoc_insertion_point(class_scope:alakoro.pb.SensingData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > data_f32_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > data_f64_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dtype_;
    ::alakoro::pb::AcquisitionMetadata* metadata_;
    uint64_t n_times_;
    uint64_t n_channels_;
    int modality_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_alakoro_5fsensing_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AcquisitionMetadata

// double sampling_rate_hz = 1;
inline void AcquisitionMetadata::clear_sampling_rate_hz() {
  _impl_.sampling_rate_hz_ = 0;
}
inline double AcquisitionMetadata::_internal_sampling_rate_hz() const {
  return _impl_.sampling_rate_hz_;
}
inline double AcquisitionMetadata::sampling_rate_hz() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.AcquisitionMetadata.sampling_rate_hz)
  return _internal_sampling_rate_hz();
}
inline void AcquisitionMetadata::_internal_set_sampling_rate_hz(double value) {
  
  _impl_.sampling_rate_hz_ = value;
}
inline void AcquisitionMetadata::set_sampling_rate_hz(double value) {
  _internal_set_sampling_rate_hz(value);
  // @@protoc_insertion_point(field_set:alakoro.pb.AcquisitionMetadata.sampling_rate_hz)
}

// double spatial_resolution_m = 2;
inline void AcquisitionMetadata::clear_spatial_resolution_m() {
  _impl_.spatial_resolution_m_ = 0;
}
inline double AcquisitionMetadata::_internal_spatial_resolution_m() const {
  return _impl_.spatial_resolution_m_;
}
inline double AcquisitionMetadata::spatial_resolution_m() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.AcquisitionMetadata.spatial_resolution_m)
  return _internal_spatial_resolution_m();
}
inline void AcquisitionMetadata::_internal_set_spatial_resolution_m(double value) {
  
  _impl_.spatial_resolution_m_ = value;
}
inline void AcquisitionMetadata::set_spatial_resolution_m(double value) {
  _internal_set_spatial_resolution_m(value);
  // @@protoc_insertion_point(field_set:alakoro.pb.AcquisitionMetadata.spatial_resolution_m)
}

// double gauge_length_m = 3;
inline void AcquisitionMetadata::clear_gauge_length_m() {
  _impl_.gauge_length_m_ = 0;
}
inline double AcquisitionMetadata::_internal_gauge_length_m() const {
  return _impl_.gauge_length_m_;
}
inline double AcquisitionMetadata::gauge_length_m() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.AcquisitionMetadata.gauge_length_m)
  return _internal_gauge_length_m();
}
inline void AcquisitionMetadata::_internal_set_gauge_length_m(double value) {
  
  _impl_.gauge_length_m_ = value;
}
inline void AcquisitionMetadata::set_gauge_length_m(double value) {
  _internal_set_gauge_length_m(value);
  // @@protoc_insertion_point(field_set:alakoro.pb.AcquisitionMetadata.gauge_length_m)
}

// string units = 4;
inline void AcquisitionMetadata::clear_units() {
  _impl_.units_.ClearToEmpty();
}
inline const std::string& AcquisitionMetadata::units() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.AcquisitionMetadata.units)
  return _internal_units();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AcquisitionMetadata::set_units(ArgT0&& arg0, ArgT... args) {
 
 _impl_.units_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:alakoro.pb.AcquisitionMetadata.units)
}
inline std::string* AcquisitionMetadata::mutable_units() {
  std::string* _s = _internal_mutable_units();
  // @@protoc_insertion_point(field_mutable:alakoro.pb.AcquisitionMetadata.units)
  return _s;
}
inline const std::string& AcquisitionMetadata::_internal_units() const {
  return _impl_.units_.Get();
}
inline void AcquisitionMetadata::_internal_set_units(const std::string& value) {
  
  _impl_.units_.Set(value, GetArenaForAllocation());
}
inline std::string* AcquisitionMetadata::_internal_mutable_units() {
  
  return _impl_.units_.Mutable(GetArenaForAllocation());
}
inline std::string* AcquisitionMetadata::release_units() {
  // @@protoc_insertion_point(field_release:alakoro.pb.AcquisitionMetadata.units)
  return _impl_.units_.Release();
}
inline void AcquisitionMetadata::set_allocated_units(std::string* units) {
  if (units != nullptr) {
    
  } else {
    
  }
  _impl_.units_.SetAllocated(units, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.units_.IsDefault()) {
    _impl_.units_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:alakoro.pb.AcquisitionMetadata.units)
}

// string start_time = 5;
inline void AcquisitionMetadata::clear_start_time() {
  _impl_.start_time_.ClearToEmpty();
}
inline const std::string& AcquisitionMetadata::start_time() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.AcquisitionMetadata.start_time)
  return _internal_start_time();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AcquisitionMetadata::set_start_time(ArgT0&& arg0, ArgT... args) {
 
 _impl_.start_time_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:alakoro.pb.AcquisitionMetadata.start_time)
}
inline std::string* AcquisitionMetadata::mutable_start_time() {
  std::string* _s = _internal_mutable_start_time();
  // @@protoc_insertion_point(field_mutable:alakoro.pb.AcquisitionMetadata.start_time)
  return _s;
}
inline const std::string& AcquisitionMetadata::_internal_start_time() const {
  return _impl_.start_time_.Get();
}
inline void AcquisitionMetadata::_internal_set_start_time(const std::string& value) {
  
  _impl_.start_time_.Set(value, GetArenaForAllocation());
}
inline std::string* AcquisitionMetadata::_internal_mutable_start_time() {
  
  return _impl_.start_time_.Mutable(GetArenaForAllocation());
}
inline std::string* AcquisitionMetadata::release_start_time() {
  // @@protoc_insertion_point(field_release:alakoro.pb.AcquisitionMetadata.start_time)
  return _impl_.start_time_.Release();
}
inline void AcquisitionMetadata::set_allocated_start_time(std::string* start_time) {
  if (start_time != nullptr) {
    
  } else {
    
  }
  _impl_.start_time_.SetAllocated(start_time, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.start_time_.IsDefault()) {
    _impl_.start_time_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:alakoro.pb.AcquisitionMetadata.start_time)
}

// -------------------------------------------------------------------

// SensingData

// .alakoro.pb.Modality modality = 1;
inline void SensingData::clear_modality() {
  _impl_.modality_ = 0;
}
inline ::alakoro::pb::Modality SensingData::_internal_modality() const {
  return static_cast< ::alakoro::pb::Modality >(_impl_.modality_);
}
inline ::alakoro::pb::Modality SensingData::modality() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.SensingData.modality)
  return _internal_modality();
}
inline void SensingData::_internal_set_modality(::alakoro::pb::Modality value) {
  
  _impl_.modality_ = value;
}
inline void SensingData::set_modality(::alakoro::pb::Modality value) {
  _internal_set_modality(value);
  // @@protoc_insertion_point(field_set:alakoro.pb.SensingData.modality)
}

// uint64 n_times = 2;
inline void SensingData::clear_n_times() {
  _impl_.n_times_ = uint64_t{0u};
}
inline uint64_t SensingData::_internal_n_times() const {
  return _impl_.n_times_;
}
inline uint64_t SensingData::n_times() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.SensingData.n_times)
  return _internal_n_times();
}
inline void SensingData::_internal_set_n_times(uint64_t value) {
  
  _impl_.n_times_ = value;
}
inline void SensingData::set_n_times(uint64_t value) {
  _internal_set_n_times(value);
  // @@protoc_insertion_point(field_set:alakoro.pb.SensingData.n_times)
}

// uint64 n_channels = 3;
inline void SensingData::clear_n_channels() {
  _impl_.n_channels_ = uint64_t{0u};
}
inline uint64_t SensingData::_internal_n_channels() const {
  return _impl_.n_channels_;
}
inline uint64_t SensingData::n_channels() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.SensingData.n_channels)
  return _internal_n_channels();
}
inline void SensingData::_internal_set_n_channels(uint64_t value) {
  
  _impl_.n_channels_ = value;
}
inline void SensingData::set_n_channels(uint64_t value) {
  _internal_set_n_channels(value);
  // @@protoc_insertion_point(field_set:alakoro.pb.SensingData.n_channels)
}

// .alakoro.pb.AcquisitionMetadata metadata = 4;
inline bool SensingData::_internal_has_metadata() const {
  return this != internal_default_instance() && _impl_.metadata_ != nullptr;
}
inline bool SensingData::has_metadata() const {
  return _internal_has_metadata();
}
inline void SensingData::clear_metadata() {
  if (GetArenaForAllocation() == nullptr && _impl_.metadata_ != nullptr) {
    delete _impl_.metadata_;
  }
  _impl_.metadata_ = nullptr;
}
inline const ::alakoro::pb::AcquisitionMetadata& SensingData::_internal_metadata() const {
  const ::alakoro::pb::AcquisitionMetadata* p = _impl_.metadata_;
  return p != nullptr ? *p : reinterpret_cast<const ::alakoro::pb::AcquisitionMetadata&>(
      ::alakoro::pb::_AcquisitionMetadata_default_instance_);
}
inline const ::alakoro::pb::AcquisitionMetadata& SensingData::metadata() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.SensingData.metadata)
  return _internal_metadata();
}
inline void SensingData::unsafe_arena_set_allocated_metadata(
    ::alakoro::pb::AcquisitionMetadata* metadata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.metadata_);
  }
  _impl_.metadata_ = metadata;
  if (metadata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:alakoro.pb.SensingData.metadata)
}
inline ::alakoro::pb::AcquisitionMetadata* SensingData::release_metadata() {
  
  ::alakoro::pb::AcquisitionMetadata* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::alakoro::pb::AcquisitionMetadata* SensingData::unsafe_arena_release_metadata() {
  // @@protoc_insertion_point(field_release:alakoro.pb.SensingData.metadata)
  
  ::alakoro::pb::AcquisitionMetadata* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
  return temp;
}
inline ::alakoro::pb::AcquisitionMetadata* SensingData::_internal_mutable_metadata() {
  
  if (_impl_.metadata_ == nullptr) {
    auto* p = CreateMaybeMessage<::alakoro::pb::AcquisitionMetadata>(GetArenaForAllocation());
    _impl_.metadata_ = p;
  }
  return _impl_.metadata_;
}
inline ::alakoro::pb::AcquisitionMetadata* SensingData::mutable_metadata() {
  ::alakoro::pb::AcquisitionMetadata* _msg = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:alakoro.pb.SensingData.metadata)
  return _msg;
}
inline void SensingData::set_allocated_metadata(::alakoro::pb::AcquisitionMetadata* metadata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.metadata_;
  }
  if (metadata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(metadata);
    if (message_arena != submessage_arena) {
      metadata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, metadata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.metadata_ = metadata;
  // @@protoc_insertion_point(field_set_allocated:alakoro.pb.SensingData.metadata)
}

// string dtype = 5;
inline void SensingData::clear_dtype() {
  _impl_.dtype_.ClearToEmpty();
}
inline const std::string& SensingData::dtype() const {
  // @@protoc_insertion_point(field_get:alakoro.pb.SensingData.dtype)
  return _internal_dtype();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SensingData::set_dtype(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dtype_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:alakoro.pb.SensingData.dtype)
}
inline std::string* SensingData::mutable_dtype() {
  std::string* _s = _internal_mutable_dtype();
  // @@protoc_insertion_point(field_mutable:alakoro.pb.SensingData.dtype)
  return _s;
}
inline const std::string& SensingData::_internal_dtype() const {
  return _impl_.dtype_.Get();
}
inline void SensingData::_internal_set_dtype(const std::string& value) {
  
  _impl_.dtype_.Set(value, GetArenaForAllocation());
}
inline std::string* SensingData::_internal_mutable_dtype() {
  
  return _impl_.dtype_.Mutable(GetArenaForAllocation());
}
inline std::string* SensingData::release_dtype() {
  // @@protoc_insertion_point(field_release:alakoro.pb.SensingData.dtype)
  return _impl_.dtype_.Release();
}
inline void SensingData::set_allocated_dtype(std::string* dtype) {
  if (dtype != nullptr) {
    
  } else {
    
  }
  _impl_.dtype_.SetAllocated(dtype, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dtype_.IsDefault()) {
    _impl_.dtype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:alakoro.pb.SensingData.dtype)
}

// repeated float data_f32 = 6;
inline int SensingData::_internal_data_f32_size() const {
  return _impl_.data_f32_.size();
}
inline int SensingData::data_f32_size() const {
  return _internal_data_f32_size();
}
inline void SensingData::clear_data_f32() {
  _impl_.data_f32_.Clear();
}
inline float SensingData::_internal_data_f32(int index) const {
  return _impl_.data_f32_.Get(index);
}
inline float SensingData::data_f32(int index) const {
  // @@protoc_insertion_point(field_get:alakoro.pb.SensingData.data_f32)
  return _internal_data_f32(index);
}
inline void SensingData::set_data_f32(int index, float value) {
  _impl_.data_f32_.Set(index, value);
  // @@protoc_insertion_point(field_set:alakoro.pb.SensingData.data_f32)
}
inline void SensingData::_internal_add_data_f32(float value) {
  _impl_.data_f32_.Add(value);
}
inline void SensingData::add_data_f32(float value) {
  _internal_add_data_f32(value);
  // @@protoc_insertion_point(field_add:alakoro.pb.SensingData.data_f32)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
SensingData::_internal_data_f32() const {
  return _impl_.data_f32_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
SensingData::data_f32() const {
  // @@protoc_insertion_point(field_list:alakoro.pb.SensingData.data_f32)
  return _internal_data_f32();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
SensingData::_internal_mutable_data_f32() {
  return &_impl_.data_f32_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
SensingData::mutable_data_f32() {
  // @@protoc_insertion_point(field_mutable_list:alakoro.pb.SensingData.data_f32)
  return _internal_mutable_data_f32();
}

// repeated double data_f64 = 7;
inline int SensingData::_internal_data_f64_size() const {
  return _impl_.data_f64_.size();
}
inline int SensingData::data_f64_size() const {
  return _internal_data_f64_size();
}
inline void SensingData::clear_data_f64() {
  _impl_.data_f64_.Clear();
}
inline double SensingData::_internal_data_f64(int index) const {
  return _impl_.data_f64_.Get(index);
}
inline double SensingData::data_f64(int index) const {
  // @@protoc_insertion_point(field_get:alakoro.pb.SensingData.data_f64)
  return _internal_data_f64(index);
}
inline void SensingData::set_data_f64(int index, double value) {
  _impl_.data_f64_.Set(index, value);
  // @@protoc_insertion_point(field_set:alakoro.pb.SensingData.data_f64)
}
inline void SensingData::_internal_add_data_f64(double value) {
  _impl_.data_f64_.Add(value);
}
inline void SensingData::add_data_f64(double value) {
  _internal_add_data_f64(value);
  // @@protoc_insertion_point(field_add:alakoro.pb.SensingData.data_f64)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
SensingData::_internal_data_f64() const {
  return _impl_.data_f64_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
SensingData::data_f64() const {
  // @@protoc_insertion_point(field_list:alakoro.pb.SensingData.data_f64)
  return _internal_data_f64();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
SensingData::_internal_mutable_data_f64() {
  return &_impl_.data_f64_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
SensingData::mutable_data_f64() {
  // @@protoc_insertion_point(field_mutable_list:alakoro.pb.SensingData.data_f64)
  return _internal_mutable_data_f64();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace alakoro

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::alakoro::pb::Modality> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::alakoro::pb::Modality>() {
  return ::alakoro::pb::Modality_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_alakoro_5fsensing_2eproto
